name: AI Bridge Lite
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_file:
    if: >
      startsWith(github.event.comment.body, '/create-file ') &&
      (
        github.actor == github.repository_owner ||
        contains(format(',{0},', vars.AI_BRIDGE_ALLOWED_ACTORS), format(',{0},', github.actor))
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse args
        id: parse
        shell: bash
        run: |
          COMMENT="${{ github.event.comment.body }}"
          ARGS="${COMMENT#'/create-file '}"
          FILEPATH=""
          CONTENT=""
          for kv in $ARGS; do
            key="${kv%%=*}"
            val="${kv#*=}"
            if [ "$key" = "path" ]; then FILEPATH="$val"; fi
            if [ "$key" = "content" ]; then CONTENT="$val"; fi
          done
          if [ -z "$FILEPATH" ] || [ -z "$CONTENT" ]; then
            echo "Missing path= or content= (base64)"; exit 1
          fi
          echo "FILEPATH=$FILEPATH" >> $GITHUB_ENV
          mkdir -p "$(dirname "$FILEPATH")"
          echo "$CONTENT" | base64 -d > "$FILEPATH"

      - name: Commit & push
        shell: bash
        run: |
          git config user.name "AI Commit Bridge"
          git config user.email "ai-bridge@users.noreply.github.com"
          git add -A
          git commit -m "AI Bridge Lite: create $FILEPATH" || echo "Nothing to commit"
          git push || true
